"""empty message

Revision ID: 204337b5456f
Revises: f4039f66f5e2
Create Date: 2026-03-28 23:35:26.397364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204337b5456f'
down_revision = 'f4039f66f5e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_seen', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'comment', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('is_seen')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
