"""Add comment flags and admin author flag

Revision ID: c26434d49a03
Revises: 204337b5456f
Create Date: 2026-03-31 22:32:56.958944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26434d49a03'
down_revision = '204337b5456f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_flagged', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('author_is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('author_is_admin')
        batch_op.drop_column('is_flagged')

    # ### end Alembic commands ###
