"""empty message

Revision ID: dde66b3fb94d
Revises: c358cb347748
Create Date: 2025-11-18 20:38:41.552862

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dde66b3fb94d"
down_revision = "c358cb347748"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blog", schema=None) as batch_op:
        batch_op.alter_column(
            "image_url", existing_type=sa.VARCHAR(length=100), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("blog", schema=None) as batch_op:
        batch_op.alter_column(
            "image_url", existing_type=sa.VARCHAR(length=100), nullable=False
        )

    # ### end Alembic commands ###
